<?php
/**
 * Hostmaster-managed subsites.
 *
 * This module links sites together with paths, allowing a site to be nested
 * under another hostmaster-managed site.
 *
 * @author Taihao Zhang (zhang.taihao@gmail.com)
 * @license GPLv2. See LICENSE.
 */

/**
 * Implementation of hook_perm.
 */
function hosting_subsite_perm() {
  return array('administer subsite');
}

/**
 * Implementation of hook_menu.
 */
function hosting_subsite_menu() {
  // Add tab to Site node view
  $items['node/%hosting_task_site/subsites'] = array(
    'title' => t('Subsites'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'hosting_subsite_subsites',
    'page arguments' => array(1),
    'file' => 'hosting_subsite.subsites.inc',
    'access' => array('administer subsite'),
    'weight' => 5,
  );
  $items['node/%hosting_task_site/subsites/%hosting_task_site/edit'] = array(
    'title' => t('Subsites'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hosting_subsite_edit_form', 1, 3),
    'file' => 'hosting_subsite.subsites.inc',
    'access' => array('administer subsite'),
    'weight' => 5,
  );
  // Autocomplete for listing potential sites to select as subsite
  $items['hosting_subsite/autocomplete/edit_subsite/%/%hosting_task_site'] = array(
    'title' => 'autocomplete edit subsite',
    'type' => MENU_CALLBACK,
    'page callback' => '_hosting_subsite_autocomplete_edit_subsite',
    'page arguments' => array(4),
    'file' => 'hosting_subsite.subsites.inc',
    'access' => array('administer subsite'),
  );

  return $items;
}

/**
 * Implementation of hook_nodeapi.
 */
function hosting_subsite_nodeapi(&$node, $op, $teaser, $page) {

}
