<?php
/**
 * Hostmaster-managed subsites.
 * This module links sites together with paths, allowing a site to be nested
 * under another hostmaster-managed site.
 *
 * @author Taihao Zhang (zhang.taihao@gmail.com)
 */

/**
 * Form controls for linking sites in site edit form.
 */
function hosting_subsite_form_hosting_site_form_alter(&$form, &$form_state) {
  $type = node_get_types('type', $node);

  $form['hosting_subsite'] = array(
    '#title' => t('Subsites'),
    '#type' => 'fieldset',
    '#tree' => TRUE,
  );
  $form['hosting_subsite'] = array(
  
  );

}

/**
 * Implementation of hook_nodeapi().
 */
function hosting_subsite_nodeapi(&$node, $op, $teaser, $page) {
  
}
